### ISSUE TITLE
Ambari Passord

### ISSUE THREAD

**Issue by jcodinal** [AlanHohn/single-node-hadoop#1]
hi,
I been trying to find out Ambari password but  any thing workout.
Jordi

**Comment by AlanHohn** [comment]
Hi Jordi,

Guessing this issue ended up in the wrong repo. Hope any thing works out.

**Comment by jcodinal** [comment]
hi,

I'm sorry if it was   my mistake.

I cant reset de password and  any of the default passwords that I found
dont  work too
it si configurated any default password or user to log in mbari?

all the other things works  amazingly. I was testing a lot of boxes  than
don't work at all..
in fact I'm inetresting to learn abaout pydoop and comand line is enouht.

thanks a lot for your a tention.

jordi

2016-01-08 1:59 GMT+01:00 Alan Hohn notifications@github.com:

**Comment by AlanHohn** [comment]
No problem, glad it's helpful to you. The Hadoop services aren't configured to need a password, and the ports are forwarded to your computer, so you can just visit http://localhost:50070 and http://localhost:8088 to see them running.

To open a console in the VM, you can just type "vagrant ssh" from the top level directory. That will log you in as the vagrant user without needing a password and you can use sudo to become root.

If you need the password for the vagrant user it's "vagrant". The password for the root user is also "vagrant".

I'm a little confused by the reference to ambari. There's no ambari here.

**Comment by jcodinal** [comment]
2016-01-08 13:04 GMT+01:00 Alan Hohn notifications@github.com:

**Comment by jcodinal** [comment]
that's true, sorry I has some web page in memory and it seems that your
vagrant box was serving an ambari server log page
I'm apologize for lost your time.

jordi

2016-01-08 13:15 GMT+01:00 Jordi Codina jcodinal@gmail.com:
